<<<<<<< HEAD
=======
// This file was generated by Prisma
>>>>>>> 489df32bf3113ab1baa32bcf354e5350bcb37174
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL!,
  },
<<<<<<< HEAD
  client: {
    output: "src/generated/prisma",
  },
});
=======
});
>>>>>>> 489df32bf3113ab1baa32bcf354e5350bcb37174
